const DriversActionTypes = {
  DRIVERS_SOCKET_ON: "DRIVERS_SOCKET_ON",
  ADD_ACTIVE_DRIVER: "ADD_ACTIVE_DRIVER",
  DRIVERS_SOCKET_OFF: "DRIVERS_SOCKET_OFF",
  SET_ACTIVE_DRIVER_POSITION: "SET_ACTIVE_DRIVER_POSITION",
  CLEAR_ACTIVE_DRIVER: "CLEAR_ACTIVE_DRIVER",
};
export default DriversActionTypes;
