const OrdersActionTypes = {
  ORDERS_SOCKET_ON: "ORDERS_SOCKET_ON",
  ORDERS_SOCKET_OFF: "ORDERS_SOCKET_OFF",
  ORDER_API_SUCCESS: "ORDER_API_SUCCESS",
  ADD_DRAG_DROP_TO_COLLECTION: "ADD_DRAG_DROP_TO_COLLECTION",
  PERSIST_ORDER_COLUMN: "PERSIST_ORDER_COLUMN",
  PERSIST_ALL_COLUMN: "PERSIST_ALL_COLUMN",
};
export default OrdersActionTypes;
