const OrdersActionTypes = {
  ORDERS_SOCKET_ON: "ORDERS_SOCKET_ON",
  ORDERS_SOCKET_OFF: "ORDERS_SOCKET_OFF",
  ORDER_API_SUCCESS: "ORDER_API_SUCCESS",
  //DRAG DROP TYPES
  INITALIZE_DRIVER_FOR_DRAG_AND_DROP: "INITALIZE_DRIVER_FOR_DRAG_AND_DROP",
  ADD_DRAG_DROP_TO_COLLECTION: "ADD_DRAG_DROP_TO_COLLECTION",
  PERSIST_ORDER_COLUMN: "PERSIST_ORDER_COLUMN",
  PERSIST_ALL_COLUMN: "PERSIST_ALL_COLUMN",
  ADD_ALL_DRIVER_TO_DRAG_AND_DROP: "ADD_ALL_DRIVER_TO_DRAG_AND_DROP",
};
export default OrdersActionTypes;
